export const FETCH_CARDS = 'FETCH_CARDS';
export const SET_CARDS_ERROR = 'SET_CARDS_ERROR';
export const FETCH_TEMPLATES = 'FETCH_TEMPLATES';
export const SET_TEMPLATES_ERROR = 'SET_TEMPLATES_ERROR';
export const CHANGE_TEMPLATE = 'CHANGE_TEMPLATE';